allowBuilds:
  dtrace-provider: false
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.24'
  - '@expo/fingerprint@0.20.13'
  - '@expo/prebuild-config@57.0.16'
  - expo-asset@57.0.17
  - expo-constants@57.0.18
  - expo-file-system@57.0.7
  - expo-font@57.0.4
  - expo-keep-awake@57.0.2
  - expo-modules-autolinking@57.0.13
  - expo-modules-core@57.0.18
  - expo@57.0.22
  - '@expo/ui@57.0.18'
  - expo-glass-effect@57.0.3
  - expo-linking@57.0.10
  - expo-router@57.0.21
  - expo-splash-screen@57.0.9
  - expo-symbols@57.0.3
  - expo-haptics@57.0.3
  - expo-application@57.0.3
  - expo-notifications@57.0.18
  - '@expo/eas-build-job@24.3.0'
  - '@expo/eas-json@24.3.0'
  - '@expo/steps@24.3.0'
  - eas-cli@24.3.0
